steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/family-letters-archive', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/family-letters-archive']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'family-letters-archive'
    - '--image'
    - 'gcr.io/$PROJECT_ID/family-letters-archive'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}'
    - '--set-secrets'
    - 'STREAMLIT_PASSWORD=streamlit-password:latest'

images:
  - 'gcr.io/$PROJECT_ID/family-letters-archive'
