[theme]
# Primary accent color for interactive elements
primaryColor = "#2E7DAF"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text
textColor = "#262730"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
# Max size of uploaded files
maxUploadSize = 200

[theme]
# The preset Streamlit theme to use
base = "light"

# Display a wider page layout
layout = "wide"
